routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\PdfMergeController;
use App\Http\Controllers\WatermarkController;
use App\Http\Controllers\PdfCompressController;
use App\Http\Controllers\PdfExtractController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('beranda');
})->name('beranda');

Route::resource('/download', DownloadController::class)
    ->only(['show']);

Route::resource('/watermark', WatermarkController::class)
    ->only(['index', 'store']);

Route::resource('/pdf/compress', PdfCompressController::class)
    ->only(['index', 'store'])
    ->names('pdf-compress');

Route::resource('/pdf/extract', PdfExtractController::class)
    ->only(['index', 'store'])
    ->names('pdf-extract');

Route::resource('/pdf/merge', PdfMergeController::class)
    ->only(['index', 'store'])
    ->names('pdf-merge');

Route::get('/fitur', function () {
    return view('fitur');
})->name('fitur');

Route::get('/privasi', function () {
    return view('privasi');
})->name('privasi');

Route::get('/sample', function () {
    return response()
        ->download((public_path('storage/img/sample_ktp.png')), 'sample_ktp.png');
});

Route::get('/files', [DownloadController::class, 'stream']);

Route::get('/files/{id}', [DownloadController::class, 'files'])
    ->name('generate_download');

resources/views/beranda.blade.php
@extends('layouts.template')

@section('content')
    <style>
        .hover-white:hover {
            color: white;
        }

    </style>
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5 px-3">
        <div class="col-12 col-sm-8 col-lg-5 d-flex justify-content-center">
            <img src="{{ asset('storage/img/doc_logo.png') }}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes"
                width="300" height="200">
        </div>
        <div class="col-lg-6">
            <h1 class="fs-1 fw-bold lh-1 mb-3 text-primary">Yakin, dokumenmu aman?</h1>
            <p class="lead">ayo tambahkan watermark untuk memberi perlindungan</p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start pt-4">
                <a href="{{ route('watermark.index') }}" class="btn btn-primary text-white btn-lg px-4 me-md-2">
                    <i class="bi bi-file-earmark-lock2-fill"></i> Beri Watermark
                </a>
                <a href="{{ route('fitur') }}" class="btn btn-outline-primary btn-lg px-4 hover-white">
                    Fitur
                </a>
            </div>
        </div>
    </div>
@endsection

resources/views/convert.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
    .page_break {
        page-break-before: always;
    }

</style>
<div style="text-align: center;">
    @php
        $i = 0;
        $len = count($images);
    @endphp
    @foreach ($images as $image)
        <img src="{{ public_path('storage/' . $image) }}" style="width: 100%" />
        @php
            if (++$i === $len) {
                break;
            }
        @endphp
        <div class="page_break"></div>
    @endforeach
</div>

resources/views/fitur.blade.php
@extends('layouts.template')

@section('title', 'Marker Plus - Fitur')
@section('content')
    <style>
        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .feature-icon {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 4rem;
            height: 4rem;
            margin-bottom: 1rem;
            font-size: 2rem;
            color: #fff;
            border-radius: .75rem;
        }

        .icon-link {
            display: inline-flex;
            align-items: center;
        }

        .icon-link>.bi {
            margin-top: .125rem;
            margin-left: .125rem;
            transition: transform .25s ease-in-out;
            fill: currentColor;
        }

        .icon-link:hover>.bi {
            transform: translate(.25rem);
        }

        .icon-square {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 3rem;
            height: 3rem;
            font-size: 1.5rem;
            border-radius: .75rem;
        }

        .rounded-4 {
            border-radius: .5rem;
        }

        .rounded-5 {
            border-radius: 1rem;
        }

        .text-shadow-1 {
            text-shadow: 0 .125rem .25rem rgba(0, 0, 0, .25);
        }

        .text-shadow-2 {
            text-shadow: 0 .25rem .5rem rgba(0, 0, 0, .25);
        }

        .text-shadow-3 {
            text-shadow: 0 .5rem 1.5rem rgba(0, 0, 0, .25);
        }

        .card-cover {
            background-repeat: no-repeat;
            background-position: center center;
            background-size: cover;
        }

    </style>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="123" viewBox="0 0 16 16">
            <path
                d="M2.873 11.297V4.142H1.699L0 5.379v1.137l1.64-1.18h.06v5.961h1.174Zm3.213-5.09v-.063c0-.618.44-1.169 1.196-1.169.676 0 1.174.44 1.174 1.106 0 .624-.42 1.101-.807 1.526L4.99 10.553v.744h4.78v-.99H6.643v-.069L8.41 8.252c.65-.724 1.237-1.332 1.237-2.27C9.646 4.849 8.723 4 7.308 4c-1.573 0-2.36 1.064-2.36 2.15v.057h1.138Zm6.559 1.883h.786c.823 0 1.374.481 1.379 1.179.01.707-.55 1.216-1.421 1.21-.77-.005-1.326-.419-1.379-.953h-1.095c.042 1.053.938 1.918 2.464 1.918 1.478 0 2.642-.839 2.62-2.144-.02-1.143-.922-1.651-1.551-1.714v-.063c.535-.09 1.347-.66 1.326-1.678-.026-1.053-.933-1.855-2.359-1.845-1.5.005-2.317.88-2.348 1.898h1.116c.032-.498.498-.944 1.206-.944.703 0 1.206.435 1.206 1.07.005.64-.504 1.106-1.2 1.106h-.75v.96Z" />
        </symbol>
        <symbol id="file-text" viewBox="0 0 16 16">
            <path
                d="M1.5 2.5A1.5 1.5 0 0 1 3 1h10a1.5 1.5 0 0 1 1.5 1.5v3.563a2 2 0 0 1 0 3.874V13.5A1.5 1.5 0 0 1 13 15H3a1.5 1.5 0 0 1-1.5-1.5V9.937a2 2 0 0 1 0-3.874V2.5zm1 3.563a2 2 0 0 1 0 3.874V13.5a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V9.937a2 2 0 0 1 0-3.874V2.5A.5.5 0 0 0 13 2H3a.5.5 0 0 0-.5.5v3.563zM2 7a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm12 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
            <path
                d="M11.434 4H4.566L4.5 5.994h.386c.21-1.252.612-1.446 2.173-1.495l.343-.011v6.343c0 .537-.116.665-1.049.748V12h3.294v-.421c-.938-.083-1.054-.21-1.054-.748V4.488l.348.01c1.56.05 1.963.244 2.173 1.496h.386L11.434 4z" />
        </symbol>
        <symbol id="file-multi" viewBox="0 0 16 16">
            <path
                d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM8.5 7v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 1 0z" />
        </symbol>
        <symbol id="file-merge" viewBox="0 0 16 16">
            <path
                d="M13 0H6a2 2 0 0 0-2 2 2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 13V4a2 2 0 0 0-2-2H5a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zM3 4a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4z" />
        </symbol>
        <symbol id="file-pdf" viewBox="0 0 16 16">
            <path
                d="M5.523 10.424c.14-.082.293-.162.459-.238a7.878 7.878 0 0 1-.45.606c-.28.337-.498.516-.635.572a.266.266 0 0 1-.035.012.282.282 0 0 1-.026-.044c-.056-.11-.054-.216.04-.36.106-.165.319-.354.647-.548zm2.455-1.647c-.119.025-.237.05-.356.078a21.035 21.035 0 0 0 .5-1.05 11.96 11.96 0 0 0 .51.858c-.217.032-.436.07-.654.114zm2.525.939a3.888 3.888 0 0 1-.435-.41c.228.005.434.022.612.054.317.057.466.147.518.209a.095.095 0 0 1 .026.064.436.436 0 0 1-.06.2.307.307 0 0 1-.094.124.107.107 0 0 1-.069.015c-.09-.003-.258-.066-.498-.256zM8.278 4.97c-.04.244-.108.524-.2.829a4.86 4.86 0 0 1-.089-.346c-.076-.353-.087-.63-.046-.822.038-.177.11-.248.196-.283a.517.517 0 0 1 .145-.04c.013.03.028.092.032.198.005.122-.007.277-.038.465z" />
            <path fill-rule="evenodd"
                d="M4 0h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm.165 11.668c.09.18.23.343.438.419.207.075.412.04.58-.03.318-.13.635-.436.926-.786.333-.401.683-.927 1.021-1.51a11.64 11.64 0 0 1 1.997-.406c.3.383.61.713.91.95.28.22.603.403.934.417a.856.856 0 0 0 .51-.138c.155-.101.27-.247.354-.416.09-.181.145-.37.138-.563a.844.844 0 0 0-.2-.518c-.226-.27-.596-.4-.96-.465a5.76 5.76 0 0 0-1.335-.05 10.954 10.954 0 0 1-.98-1.686c.25-.66.437-1.284.52-1.794.036-.218.055-.426.048-.614a1.238 1.238 0 0 0-.127-.538.7.7 0 0 0-.477-.365c-.202-.043-.41 0-.601.077-.377.15-.576.47-.651.823-.073.34-.04.736.046 1.136.088.406.238.848.43 1.295a19.707 19.707 0 0 1-1.062 2.227 7.662 7.662 0 0 0-1.482.645c-.37.22-.699.48-.897.787-.21.326-.275.714-.08 1.103z" />
        </symbol>
        <symbol id="file-compress" viewBox="0 0 16 16">
            <path
                d="M6.5 7.5a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v.938l.4 1.599a1 1 0 0 1-.416 1.074l-.93.62a1 1 0 0 1-1.109 0l-.93-.62a1 1 0 0 1-.415-1.074l.4-1.599V7.5zm2 0h-1v.938a1 1 0 0 1-.03.243l-.4 1.598.93.62.93-.62-.4-1.598a1 1 0 0 1-.03-.243V7.5z" />
            <path
                d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm5.5-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9v1H8v1h1v1H8v1h1v1H7.5V5h-1V4h1V3h-1V2h1V1z" />
        </symbol>
        <symbol id="file-extract" viewBox="0 0 16 16">
            <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
            <path
                d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2zM14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1zM2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1h-10z" />
        </symbol>
    </svg>

    <div class="container px-4 py-5" id="featured-3">
        <h2 class="pb-2 text-primary">Kami <b>tidak hanya</b> menambah watermark !</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#file-text"></use>
                    </svg>
                </div>
                <div>
                    <h3 class="text-primary">Watermark</h3>
                    <p>tentu saja, bisa menambah <b class="text-primary">text</b> watermark secara <b
                            class="text-primary">otomatis</b> yang disertai tanggal</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#file-multi"></use>
                    </svg>
                </div>
                <div>
                    <h3 class="text-primary">Multiple</h3>
                    <p>kamu juga bisa upload <b class="text-primary">lebih dari satu</b> file dokumen atau gambar pada <b
                            class="text-primary">saat bersamaan</b>
                    </p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#file-merge"></use>
                    </svg>
                </div>
                <div>
                    <h3 class="text-primary">Merge</h3>
                    <p>setelahnya kami akan <b class="text-primary">menggabungkan</b> semua slide dokumen serta gambar <b
                            class="text-primary">menjadi satu</b></p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#file-pdf"></use>
                    </svg>
                </div>
                <div>
                    <h3 class="text-primary">Hasil PDF</h3>
                    <p>dan hasilnya, akan di <b class="text-primary">konversi</b> menjadi <b class="text-primary">file
                            pdf</b> yang mudah untuk diunduh
                        dan dibagikan kedepannya.
                    </p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#file-compress"></use>
                    </svg>
                </div>
                <div>
                    <h3 class="text-primary">Kompresi</h3>
                    <p>saat di dukung, file kamu juga akan secara <b class="text-primary">otomatis di kompresi</b> sekecil
                        mungkin
                        tanpa
                        mengurangi
                        kualitasnya.</p>
                    </p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#file-extract"></use>
                    </svg>
                </div>
                <div>
                    <h3 class="text-primary">Ekstrak</h3>
                    <p>jika dipilih, setiap <b class="text-primary">bagian</b> dari <b class="text-primary">file pdf</b>
                        kamu juga akan kami <b class="text-primary">ekstrak</b>
                        menjadi <b class="text-primary">gambar</b> kedalam arsip
                        zip</p>
                    </p>
                </div>
            </div>
        </div>
        <h4 class="pb-2 text-primary">serta fitur lainnya yang akan datang..</h4>
    </div>
@endsection

resources/views/privasi.blade.php
@extends('layouts.template')

@section('title', 'Marker Plus - Privasi')
@section('content')
    <style>
        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .feature-icon {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 4rem;
            height: 4rem;
            margin-bottom: 1rem;
            font-size: 2rem;
            color: #fff;
            border-radius: .75rem;
        }

        .icon-link {
            display: inline-flex;
            align-items: center;
        }

        .icon-link>.bi {
            margin-top: .125rem;
            margin-left: .125rem;
            transition: transform .25s ease-in-out;
            fill: currentColor;
        }

        .icon-link:hover>.bi {
            transform: translate(.25rem);
        }

        .icon-square {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 3rem;
            height: 3rem;
            font-size: 1.5rem;
            border-radius: .75rem;
        }

        .rounded-4 {
            border-radius: .5rem;
        }

        .rounded-5 {
            border-radius: 1rem;
        }

        .text-shadow-1 {
            text-shadow: 0 .125rem .25rem rgba(0, 0, 0, .25);
        }

        .text-shadow-2 {
            text-shadow: 0 .25rem .5rem rgba(0, 0, 0, .25);
        }

        .text-shadow-3 {
            text-shadow: 0 .5rem 1.5rem rgba(0, 0, 0, .25);
        }

        .card-cover {
            background-repeat: no-repeat;
            background-position: center center;
            background-size: cover;
        }

    </style>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="anonim" viewBox="0 0 16 16">
            <path
                d="M13.359 11.238C15.06 9.72 16 8 16 8s-3-5.5-8-5.5a7.028 7.028 0 0 0-2.79.588l.77.771A5.944 5.944 0 0 1 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.134 13.134 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755-.165.165-.337.328-.517.486l.708.709z" />
            <path
                d="M11.297 9.176a3.5 3.5 0 0 0-4.474-4.474l.823.823a2.5 2.5 0 0 1 2.829 2.829l.822.822zm-2.943 1.299.822.822a3.5 3.5 0 0 1-4.474-4.474l.823.823a2.5 2.5 0 0 0 2.829 2.829z" />
            <path
                d="M3.35 5.47c-.18.16-.353.322-.518.487A13.134 13.134 0 0 0 1.172 8l.195.288c.335.48.83 1.12 1.465 1.755C4.121 11.332 5.881 12.5 8 12.5c.716 0 1.39-.133 2.02-.36l.77.772A7.029 7.029 0 0 1 8 13.5C3 13.5 0 8 0 8s.939-1.721 2.641-3.238l.708.709zm10.296 8.884-12-12 .708-.708 12 12-.708.708z" />
        </symbol>
        <symbol id="lock" viewBox="0 0 16 16">
            <path
                d="M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z" />
            <path
                d="M9.5 6.5a1.5 1.5 0 0 1-1 1.415l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99a1.5 1.5 0 1 1 2-1.415z" />
        </symbol>
        <symbol id="temp" viewBox="0 0 16 16">
            <path
                d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z" />
            <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z" />
            <path
                d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z" />
        </symbol>
    </svg>

    <div class="container px-4 py-5" id="featured-3">
        <h2 class="pb-2 text-primary"><b>Menjaga privasi</b> kamu, itu tujuan kami.</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#anonim"></use>
                    </svg>
                </div>
                <div>
                    <h2 class="text-primary">Anonim</h2>
                    <p>kamu tidak perlu <b class="text-primary">login</b> dan mengisi <b class="text-primary">nama,
                            email</b> serta data pribadi lainnya.</p>
                    <p>semua dilakukan secara anonim..</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#lock"></use>
                    </svg>
                </div>
                <div>
                    <h2 class="text-primary">Aman</h2>
                    <p>hasil file kamu akan <b class="text-primary">dienkripsi</b> oleh <b
                            class="text-primary">FileVault</b> dan hanya bisa
                        dilihat saat kamu
                        selesai <b class="text-primary">mengunduhnya.</b></p>
                    <p>bebas dari pencurian data server..</p>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div class="icon-square bg-primary text-white flex-shrink-0 me-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#temp"></use>
                    </svg>
                </div>
                <div>
                    <h2 class="text-primary">Sementara</h2>
                    <p>kami menyimpan file maksimal <b class="text-primary">hanya 3 menit</b> setelah itu kami jamin akan
                        <b class="text-primary">hapus</b>
                        sepenuhnya.
                    </p>
                    <p>bebas dari cracking data lawas..</p>
                </div>
            </div>
        </div>
        <h6 class="pb-2 text-primary">
            dan juga ketentuan dari
            <a href="https://www.convertapi.com/terms" target="_blank" class="text-decoration-none"><b>ConvertAPI.</b></a>
        </h6>
    </div>
@endsection