routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\PdfMergeController;
use App\Http\Controllers\WatermarkController;
use App\Http\Controllers\PdfCompressController;
use App\Http\Controllers\PdfExtractController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('beranda');
})->name('beranda');

Route::resource('/download', DownloadController::class)
    ->only(['show']);

Route::resource('/watermark', WatermarkController::class)
    ->only(['index', 'store']);

Route::resource('/pdf/compress', PdfCompressController::class)
    ->only(['index', 'store'])
    ->names('pdf-compress');

Route::resource('/pdf/extract', PdfExtractController::class)
    ->only(['index', 'store'])
    ->names('pdf-extract');

Route::resource('/pdf/merge', PdfMergeController::class)
    ->only(['index', 'store'])
    ->names('pdf-merge');

Route::get('/fitur', function () {
    return view('fitur');
})->name('fitur');

Route::get('/privasi', function () {
    return view('privasi');
})->name('privasi');

Route::get('/sample', function () {
    return response()
        ->download((public_path('storage/img/sample_ktp.png')), 'sample_ktp.png');
});

Route::get('/files', [DownloadController::class, 'stream']);

Route::get('/files/{id}', [DownloadController::class, 'files'])
    ->name('generate_download');

app/Http/Controllers/WatermarkController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\StorageFile;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Jobs\ExpiredStorageFile;
use Barryvdh\DomPDF\Facade as PDF;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use SoareCostin\FileVault\Facades\FileVault;
use Illuminate\Support\Facades\Http;

class WatermarkController extends Controller
{
    public function index()
    {
        return view('watermark.index');
    }

    public function store(Request $request)
    {
        // validate
        $request->validate([
            'tujuan' => 'required|string|max:60',
            'files.*' => 'required|mimes:jpeg,png,jpg,pdf,doc,docx,xls,xlsx,ppt,pptx',
            'extract' => 'nullable'
        ]);

        // check extension file
        $first = true;
        $original_size = 0;
        foreach ($request->file('files') as $file) {
            if ($first == true) {
                // get original filename without extension
                $original_filename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $first = false;
            }
            $original_size += $file->getSize();
            $extension = $file->getClientOriginalExtension();

            $response = Http::attach('File', file_get_contents($file), Str::random(5) . '.' . $extension);
            $response = $response->post("https://v2.convertapi.com/convert/" . $extension . "/to/pdf?Secret=" . secretkey());
            // check response status code not 200
            if ($response->status() != 200) {
                return 'Terjadi masalah pada sistem, silahkan coba lagi.';
            }
            $pdf_files[] = base64_decode(json_decode($response->body())->Files[0]->FileData);
        }

        // merge pdf if pdf_file > 1
        if (count($pdf_files) > 1) {
            $response = Http::withoutRedirecting();
            foreach ($pdf_files as $i => $pdf) {
                $response = $response->attach('Files[' . $i . ']', $pdf, Str::random(5) . '.pdf');
            }
            $response = $response->post("https://v2.convertapi.com/convert/pdf/to/merge?Secret=" . secretkey());
            // check response status code not 200
            if ($response->status() != 200) {
                return 'Terjadi masalah pada sistem, silahkan coba lagi.';
            }
            $pdf = base64_decode(json_decode($response->body())->Files[0]->FileData);
        } else {
            $pdf = $pdf_files[0];
        }

        // get today's date dd-mm-yyyy using carbon
        $date = Carbon::now()->format('d-m-Y');

        // watermark pdf
        $response  = Http::attach('File', $pdf, Str::random(5) . '.pdf');
        $response = $response->post("https://v2.convertapi.com/convert/pdf/to/watermark?Secret=" . secretkey(), [
            'Text' => $date . '%N%%N%'  . $request->tujuan, // text watermark
            'TextAlign' => 'center',
            'WordWrap' => 'true',
            'TextRenderingMode' => 'stroketext',
            'FontSize' => '25', // font size
            'Opacity' => '20'
        ]);

        // check response status code not 200
        if ($response->status() != 200) {
            return 'Terjadi masalah pada sistem, silahkan coba lagi.';
        }

        $response = base64_decode(json_decode($response->body())->Files[0]->FileData);

        // compress pdf
        $response = Http::attach('File', $response, Str::random(10) . '.pdf')
            ->post("https://v2.convertapi.com/convert/pdf/to/compress?Secret=" . secretkey(), [
                'ColorImageQuality' => 70,
                'ColorImageDownsample' => 'true',
                'GrayscaleImageQuality' => 70,
                'GrayscaleImageDownsample' => 'true',
            ]);

        // check response status code not 200
        if ($response->status() != 200) {
            return 'Terjadi masalah pada sistem, silahkan coba lagi.';
        }

        $response = base64_decode(json_decode($response->body())->Files[0]->FileData);

        // extract image from pdf
        $extension = 'pdf';
        if ($request->extract == True) {
            $response = $this->extract($response, $original_filename);
            $extension = 'zip';
        }

        // generate encrypted filename
        $encrypt_path = 'files/' . Str::random(50) . ".$extension";

        // save response to local storage
        Storage::disk('local')->put($encrypt_path, $response);
        $size = Storage::disk('local')->size($encrypt_path);

        // encrypt file
        FileVault::encrypt($encrypt_path);

        $expired = Carbon::now()->addMinute(3);

        // save to table storage_files
        $file = StorageFile::create([
            'encrypt_path' => $encrypt_path . '.enc',
            'original_filename' => str_replace(' ', '_', $original_filename) . '_markerplus.' . $extension,
            'original_size' => $original_size,
            'size' => $size,
            'expired_at' => $expired
        ]);

        // dispatch job to expired file
        ExpiredStorageFile::dispatch($file)->delay($expired);

        // redirect to download page
        return redirect()->route('download.show', $file->id);
    }
    private function extract($file, $original_filename)
    {
        $response = Http::attach('File', $file, Str::random(10) . '.pdf')
            ->post("https://v2.convertapi.com/convert/pdf/to/jpg?Secret=" . secretkey());

        // check response status code not 200
        if ($response->status() != 200) {
            return 'Terjadi masalah pada sistem, silahkan coba lagi.';
        }

        $response_body = json_decode($response->body())->Files;

        $response = Http::withoutRedirecting();
        foreach ($response_body as $i => $file) {
            $file = base64_decode($file->FileData);
            $response = $response->attach('Files[' . $i . ']', $file, $original_filename . "_($i).jpg");
        }

        $response = $response->post("https://v2.convertapi.com/convert/any/to/zip?Secret=" . secretkey());
        $response = base64_decode(json_decode($response->body())->Files[0]->FileData);

        return $response;
    }
}

resources/views/watermark/banner.blade.php
<style>
    .blink {
        animation: blinker 0.7s linear infinite;
    }

    @keyframes blinker {
        50% {
            opacity: 0;
        }
    }

</style>
<div class="p-4">
    <img class="d-block mx-auto mb-4" src="{{ asset('storage/img/docu_logo.gif') }}" alt="" width="92" height="72">
    <h1 class="fs-2 fw-bold text-center text-primary">
        Waterm<span class="blink">|</span><span class="text-secondary opacity-25">ark <sup>+</sup></span>
    </h1>
</div>

resources/views/watermark/index.blade.php
@extends('layouts.template')

@section('title', 'Marker Plus - Watermark')
@section('content')
    <div class="mt-5 mb-3">
        @include('watermark.banner')

        <div class="col-12 col-md-8 col-lg-6 d-block mx-auto my-3">
            <div class="progress my-2" style="height: 5px;">
                <div id="progress" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                    style="width: 0%">
                </div>
            </div>
            <form action="{{ route('watermark.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card shadow border-0 p-3">
                    <div class="card-body">
                        <div class="mb-3">
                            <label class="form-label">Untuk tujuan apa?</label>
                            <input type="text" id="tujuan" name="tujuan"
                                class="form-control @error('tujuan') is-invalid @enderror" value="{{ old('tujuan') }}">
                            @error('tujuan')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="mb-4">
                            <label class="form-label">Pilih dokumen atau gambar</label>
                            <input class="form-control @error('files.*') is-invalid @enderror" type="file" name="files[]"
                                accept="image/jpeg, image/png, image/jpg, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, capture=camera"
                                multiple required>
                            <div class="form-text">bisa lebih dari satu namun hasil akan digabung.</div>
                            @error('files.*')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="extract">
                            <label class="form-check-label">
                                Ekstrak hasilnya kedalam bentuk gambar
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" checked onclick="return false;">
                            <label class="form-check-label">
                                Setuju dengan <a href="{{ route('privasi') }}" target="_blank"
                                    class="text-decoration-none">ketentuan dan privasi</a>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="my-5 text-center">
                    <button type="submit" class="btn btn-primary text-white col-10 col-md-5">
                        <i class="bi bi-magic"></i> PROSES
                    </button>
                </div>
            </form>
        </div>
    </div>

    <script>
        // Placeholder Type Witter by lankovova

        function addToPlaceholder(toAdd, el) {
            el.attr('placeholder', el.attr('placeholder') + toAdd);
            return new Promise(resolve => setTimeout(resolve, 100));
        }

        function clearPlaceholder(el) {
            el.attr("placeholder", "");
        }

        function printPhrase(phrase, el) {
            return new Promise(resolve => {
                clearPlaceholder(el);
                let letters = phrase.split('');
                letters.reduce(
                    (promise, letter, index) => promise.then(_ => {
                        if (index === letters.length - 1) {
                            setTimeout(resolve, 1000);
                        }
                        return addToPlaceholder(letter, el);
                    }),
                    Promise.resolve()
                );
            });
        }


        function printPhrases(phrases, el) {
            phrases.reduce(
                (promise, phrase) => promise.then(_ => printPhrase(phrase, el)),
                Promise.resolve()
            );
        }

        // Start typing
        function run() {
            let phrases = [
                "Verifikasi akun e-commerce",
                "Verifikasi pendaftaran Paypal",
                "Lamaran pada PT. Marker Plus",
                "Tentukan tujuanmu apapun itu..",
            ];

            printPhrases(phrases, $('#tujuan'));
        }

        run();
    </script>
    @include('layouts.submit')
@endsection